### ISSUE TITLE
O arquivo AulaManha.ipynb atualizado fora da pasta material

### ISSUE THREAD

**Issue by marcelomiky** [grupy-sanca/curso-python-intro#3]
Como faz?

**Comment by lamenezes** [comment]
Pode deixar que eu ajeito isso, enquanto isso vai aprendendo a usar o git
kraken [1], é bem tranquilo.

[1] https://www.gitkraken.com/

**Comment by lamenezes** [comment]
Resolvido no commit 0e9557870248b103ee68d5578ca910a0cdae544b
