### ISSUE TITLE
Mudar o nome das aulas para algo mais significativo

### ISSUE THREAD

**Issue by tiagoamartins** [grupy-sanca/curso-python-intro#7]
Tava pensando em mudar o nome das aulas para algo mais significativo. Porque eu nem tinha visto que a **Parte 2** já tinha o conteúdo de _listas_. Eu estava pensando em colocar algo do tipo "01 - Básico", "02 - Listas"... Que tal?

**Comment by marcelomiky** [comment]
Uma boa, Tiago!

**Comment by marcelomiky** [comment]
Alterei os nomes, mas pensando aqui devia ter feito isso depois dos PR.
